### PR TITLE
Update intel-mkl-src 0.4.0

### PR DESCRIPTION
**Pull request by termoshtt**
- Windows support
- pkg-config support

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
Any chance this could land and have a new release cut, @IvanUkhov ?

**Comment by IvanUkhov** [comment]
Sorry for the delay!

**Comment by waywardmonkeys** [comment]
Thanks! Have a PR now into `nalgebra-lapack` to update to the newly published version.

**Comment by IvanUkhov** [comment]
@termoshtt, you actually have write access to all `-src` repositories in this organization, and now you should also be able publish `blas-src` and `lapack-src` on `crates.io` on your own. Please feel free to make changes as you see fit, as I might forget and unintentionally cause delays.

**Comment by IvanUkhov** [comment]
Any idea why `intel-mkl` fails on macOS?

https://travis-ci.org/blas-lapack-rs/blas-src/builds/542312996

https://travis-ci.org/blas-lapack-rs/lapack-src/builds/542312616

Should this pull request be reverted?

**Comment by astraw** [comment]
How is Travis caching? 

The errors like 

    error[E0277]: the trait bound `rand_hc::Hc128Rng: rand_core::SeedableRng` is not satisfied

look like perhaps something going wrong with `rand` and its dependencies. I don't see how Intel MKL could have anything to do with these errors. Perhaps putting a `cargo update` into the `.travis.yml` will fix this?

**Comment by IvanUkhov** [comment]
I’ve cleared the cache and restarted the build. Two out of six have already passed.

**Comment by IvanUkhov** [comment]
All green. Thanks for the tip!

**Comment by termoshtt** [comment]
> Please feel free to make changes as you see fit, as I might forget and unintentionally cause delays.

I see. I will do next time, thanks.

**Pull request merged**
